version: '3.1'
services:
#  mongodb:
#    image: 'mongo:3.6'
#    ports:
#      - "27017:27017"
#    volumes:
#      - /Users/edh/DockerProjects/mongodb/data:/data/db
#    networks:
#      - vdek
#    hostname: mongodb
  vdekmock:
    image: edhi/vdekmock:latest
    networks:
      - vdek
    hostname: vdekmock
    ports:
      - "8080:8080"
    environment:
      LOGSTASH_ADDRESS: ${LOGSTASH_ADDRESS:-127.0.0.1:5000}
#      MONGODB_HOST: ${MONGODB_HOST:-mongodb}
#      MONGODB_PORT: ${MONGODB_PORT:-27017}
#    depends_on:
#      - mongodb
  vdekmockadaptor:
    image: edhi/vdekmockadaptor:latest
    networks:
      - vdek
    hostname: vdekmockadaptor
    ports:
      - "4444:4444"
    environment:
      VDEK_MOCK_ADDRESS: ${VDEK_MOCK_ADDRESS:-vdekmock:8080}
      LOGSTASH_ADDRESS: ${LOGSTASH_ADDRESS:-127.0.0.1:5000}
    depends_on:
      - vdekmock
networks:
  vdek:
    driver: bridge