apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: vdekmock
  name: vdekmock
spec:
  ports:
  - name: "8080"
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: vdekmock
status:
  loadBalancer: {}
