apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdek-mock-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vdek-mock
  template:
    metadata:
      labels:
        app: vdek-mock
    spec:
      containers:
      - name: vdek-mock
        image: edhi/vdekmock:latest
        ports:
        - containerPort: 8080


---
kind: Service
apiVersion: v1
metadata:
  name: vdek-mock-deployment
spec:
  # Make the service externally visible via the node
  type: NodePort 

  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30091

  selector:
    app: vdek-mock