apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: vdekmockadaptor
  name: vdekmockadaptor
spec:
  ports:
  - name: "4444"
    protocol: TCP
    port: 4444
    targetPort: 4444
  selector:
    io.kompose.service: vdekmockadaptor
status:
  loadBalancer: {}
