apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vdekadaptor
  namespace: vdek
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        name: vdekadaptor
    
    spec:
      containers:
      - image: edhi/vdekmockadaptor:latest
        name: vdekadaptor
        ports:
        - containerPort: 4444
        env:
        - name: VDEK_MOCK_ADDRESS
          value: vdekmock:8080
        - name: LOGSTASH_ADDRESS
          value: logstash.vdek.spronq.com:5000
      hostname: vdekadaptor
      restartPolicy: Always

