apiVersion: v1
kind: Service
metadata:
  name: vdekadaptor
  namespace: vdek
spec:
  ports:
  - name: "4444"
    protocol: TCP
    port: 4444
    targetPort: 4444
  selector:
    name: vdekadaptor
status:
  loadBalancer: {}
