apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vdekmock
  namespace: vdek
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        name: vdekmock
    
    spec:
      containers:
      - image: edhi/vdekmock:latest
        name: vdekmock
        ports:
        - containerPort: 8080
        env:
        - name: LOGSTASH_ADDRESS
          value: logstash.elk:5000
      hostname: vdekmock
      restartPolicy: Always
